from collections import deque
import time


class LiveMetrics:
    def __init__(self, max_history=200):
        self.history = deque(maxlen=max_history)
        self.nod_count = 0
        self.last_nod_time = 0

    def update(self, frame):
        now = time.time()

        if "nod_count_override" in frame:
            self.nod_count = frame["nod_count_override"]
        elif frame.get("nod_detected", False):
            if now - self.last_nod_time > 1.0:
                self.nod_count += 1
                self.last_nod_time = now

        item = {
            "timestamp": frame.get("timestamp", now),
            "stream_uptime_sec": frame.get("stream_uptime_sec", 0),
            "stream_profile_name": frame.get("stream_profile_name", "unknown"),
            "stream_profile_error": frame.get("stream_profile_error"),
            "eye_stream_status": frame.get("eye_stream_status", "waiting_for_eye_track"),
            "eye_wait_sec": frame.get("eye_wait_sec", 0),
            "eye_start_delay_sec": frame.get("eye_start_delay_sec"),
            "eye_fps_est": frame.get("eye_fps_est", 0),
            "heart_rate_bpm": frame.get("heart_rate_bpm"),
            "heart_rate_connected": frame.get("heart_rate_connected", False),
            "heart_rate_timestamp": frame.get("heart_rate_timestamp"),
            "heart_rate_port": frame.get("heart_rate_port"),
            "heart_rate_raw_line": frame.get("heart_rate_raw_line"),
            "raw_imu_timestamp_ns": frame.get("raw_imu_timestamp_ns"),
            "raw_imu_timestamp_sec": frame.get("raw_imu_timestamp_sec"),
            "raw_imu_index": frame.get("raw_imu_index"),
            "raw_accel_x_msec2": frame.get("raw_accel_x_msec2"),
            "raw_accel_y_msec2": frame.get("raw_accel_y_msec2"),
            "raw_accel_z_msec2": frame.get("raw_accel_z_msec2"),
            "raw_gyro_x_radsec": frame.get("raw_gyro_x_radsec"),
            "raw_gyro_y_radsec": frame.get("raw_gyro_y_radsec"),
            "raw_gyro_z_radsec": frame.get("raw_gyro_z_radsec"),
            "raw_mag_x_tesla": frame.get("raw_mag_x_tesla"),
            "raw_mag_y_tesla": frame.get("raw_mag_y_tesla"),
            "raw_mag_z_tesla": frame.get("raw_mag_z_tesla"),
            "raw_eye_timestamp_ns": frame.get("raw_eye_timestamp_ns"),
            "raw_eye_camera_id": frame.get("raw_eye_camera_id"),
            "raw_eye_width": frame.get("raw_eye_width"),
            "raw_eye_height": frame.get("raw_eye_height"),
            "raw_eye_channels": frame.get("raw_eye_channels"),
            "raw_eye_dtype": frame.get("raw_eye_dtype"),
            "raw_eye_mean": frame.get("raw_eye_mean"),
            "raw_eye_std": frame.get("raw_eye_std"),
            "raw_eye_frame_count": frame.get("raw_eye_frame_count", 0),

            "blink_rate_bpm": frame.get("blink_rate_bpm", 0),
            "blink_count": frame.get("blink_count", 0),
            "perclos": frame.get("perclos", 0),
            "perclos80_true": frame.get("perclos80_true", frame.get("perclos", 0)),
            "perclos_continuous_pct": frame.get("perclos_continuous_pct", frame.get("closure_mean_pct", 0)),
            "perclos_source": frame.get("perclos_source", "unknown"),
            "true_perclos": frame.get("true_perclos", frame.get("perclos", 0)),
            "true_perclos_raw": frame.get("true_perclos_raw", frame.get("true_perclos", 0)),
            "closure_pct": frame.get("closure_pct", frame.get("true_perclos_raw", 0)),
            "closed80": frame.get("closed80", False),
            "pupil_found": frame.get("pupil_found", False),
            "pupil_area_px": frame.get("pupil_area_px", 0),
            "pupil_score": frame.get("pupil_score", 0),
            "pupil_circularity": frame.get("pupil_circularity", 0),
            "area_ref": frame.get("area_ref", 0),
            "raw_eye_state": frame.get("raw_eye_state", "unknown"),
            "final_smoothed_eye_state": frame.get("final_smoothed_eye_state", "unknown"),
            "valid_eye_fraction": frame.get("valid_eye_fraction", 0),
            "closure_mean_pct": frame.get("closure_mean_pct", 0),
            "visible_iris_area": frame.get("visible_iris_area", 0),
            "baseline_iris_area": frame.get("baseline_iris_area", 0),
            "visible_iris_ratio": frame.get("visible_iris_ratio", 0),
            "eye_calibrated": frame.get("eye_calibrated", False),
            "eye_segmentation_ok": frame.get("eye_segmentation_ok", False),
            "eye_status": frame.get("eye_status", "unknown"),
            "eye_confidence": frame.get("eye_confidence", 0),
            "eye_roi_mean": frame.get("eye_roi_mean", 0),
            "eye_roi_std": frame.get("eye_roi_std", 0),
            "eye_edge_density": frame.get("eye_edge_density", 0),
            "eye_mask_area_ratio": frame.get("eye_mask_area_ratio", 0),
            "eye_frame_errors": frame.get("eye_frame_errors", 0),
            "eye_data_age_ms": frame.get("eye_data_age_ms"),
            "eye_debug_enabled": frame.get("eye_debug_enabled", False),
            "eye_classifier_available": frame.get("eye_classifier_available", False),
            "eye_classifier_state": frame.get("eye_classifier_state", "unavailable"),
            "eye_classifier_confidence": frame.get("eye_classifier_confidence", 0),
            "eye_classifier_error": frame.get("eye_classifier_error"),
            "eye_closed_prob": frame.get("eye_closed_prob", 0),
            "eye_open_prob": frame.get("eye_open_prob", 0),
            "eye_blink_prob": frame.get("eye_blink_prob", 0),
            "frame_closure_ratio": frame.get("frame_closure_ratio", 0),
            "eye_closed": frame.get("eye_closed", False),
            "closed_frames": frame.get("closed_frames", 0),
            "open_frames": frame.get("open_frames", 0),
            "eye_closed_frames": frame.get("eye_closed_frames", frame.get("closed_frames", 0)),
            "eye_open_frames": frame.get("eye_open_frames", frame.get("open_frames", 0)),
            "total_frames": frame.get("total_frames", 0),
            "microsleep_count": frame.get("microsleep_count", 0),
            "microsleep_active": frame.get("microsleep_active", False),
            "microsleep_closed_duration_sec": frame.get("microsleep_closed_duration_sec", 0),

            "fatigue_score": frame.get("fatigue_score", 0),

            "yaw_deg": frame.get("yaw_deg", 0),
            "pitch_deg": frame.get("pitch_deg", 0),
            "roll_deg": frame.get("roll_deg", 0),
            "imu_selected_idx": frame.get("imu_selected_idx"),
            "imu_last_idx": frame.get("imu_last_idx"),
            "imu_processed_samples": frame.get("imu_processed_samples", 0),
            "imu_skipped_samples": frame.get("imu_skipped_samples", 0),
            "imu_pitch_raw_deg": frame.get("imu_pitch_raw_deg", 0),
            "imu_roll_raw_deg": frame.get("imu_roll_raw_deg", 0),
            "imu_pitch_gravity_deg": frame.get("imu_pitch_gravity_deg", 0),
            "imu_roll_gravity_deg": frame.get("imu_roll_gravity_deg", 0),
            "imu_pitch_zero_deg": frame.get("imu_pitch_zero_deg", 0),
            "imu_roll_zero_deg": frame.get("imu_roll_zero_deg", 0),
            "imu_neutral_calibrated": frame.get("imu_neutral_calibrated", False),
        }

        self.history.append(item)
    
    def reset_all(self):
        self.history.clear()
        self.nod_count = 0
        self.last_nod_time = 0
    
    def reset_nods(self):
        self.nod_count = 0
        self.last_nod_time = 0

    def latest_payload(self):
        latest = self.history[-1] if self.history else {
            "timestamp": time.time(),
            "stream_uptime_sec": 0,
            "stream_profile_name": "unknown",
            "stream_profile_error": None,
            "eye_stream_status": "waiting_for_data",
            "eye_wait_sec": 0,
            "eye_start_delay_sec": None,
            "eye_fps_est": 0,
            "heart_rate_bpm": None,
            "heart_rate_connected": False,
            "heart_rate_timestamp": None,
            "heart_rate_port": None,
            "heart_rate_raw_line": None,
            "raw_imu_timestamp_ns": None,
            "raw_imu_timestamp_sec": None,
            "raw_imu_index": None,
            "raw_accel_x_msec2": None,
            "raw_accel_y_msec2": None,
            "raw_accel_z_msec2": None,
            "raw_gyro_x_radsec": None,
            "raw_gyro_y_radsec": None,
            "raw_gyro_z_radsec": None,
            "raw_mag_x_tesla": None,
            "raw_mag_y_tesla": None,
            "raw_mag_z_tesla": None,
            "raw_eye_timestamp_ns": None,
            "raw_eye_camera_id": None,
            "raw_eye_width": None,
            "raw_eye_height": None,
            "raw_eye_channels": None,
            "raw_eye_dtype": None,
            "raw_eye_mean": None,
            "raw_eye_std": None,
            "raw_eye_frame_count": 0,

            "blink_rate_bpm": 0,
            "blink_count": 0,
            "perclos": 0,
            "perclos80_true": 0,
            "perclos_continuous_pct": 0,
            "perclos_source": "waiting_for_data",
            "true_perclos": 0,
            "true_perclos_raw": 0,
            "closure_pct": 0,
            "closed80": False,
            "pupil_found": False,
            "pupil_area_px": 0,
            "pupil_score": 0,
            "pupil_circularity": 0,
            "area_ref": 0,
            "raw_eye_state": "unknown",
            "final_smoothed_eye_state": "unknown",
            "valid_eye_fraction": 0,
            "closure_mean_pct": 0,
            "visible_iris_area": 0,
            "baseline_iris_area": 0,
            "visible_iris_ratio": 0,
            "eye_calibrated": False,
            "eye_segmentation_ok": False,
            "eye_status": "waiting_for_data",
            "eye_confidence": 0,
            "eye_roi_mean": 0,
            "eye_roi_std": 0,
            "eye_edge_density": 0,
            "eye_mask_area_ratio": 0,
            "eye_frame_errors": 0,
            "eye_data_age_ms": None,
            "eye_debug_enabled": False,
            "eye_classifier_available": False,
            "eye_classifier_state": "unavailable",
            "eye_classifier_confidence": 0,
            "eye_classifier_error": None,
            "eye_closed_prob": 0,
            "eye_open_prob": 0,
            "eye_blink_prob": 0,
            "frame_closure_ratio": 0,
            "eye_closed": False,
            "closed_frames": 0,
            "open_frames": 0,
            "eye_closed_frames": 0,
            "eye_open_frames": 0,
            "total_frames": 0,
            "microsleep_count": 0,
            "microsleep_active": False,
            "microsleep_closed_duration_sec": 0,

            "fatigue_score": 0,

            "yaw_deg": 0,
            "pitch_deg": 0,
            "roll_deg": 0,
            "imu_selected_idx": None,
            "imu_last_idx": None,
            "imu_processed_samples": 0,
            "imu_skipped_samples": 0,
            "imu_pitch_raw_deg": 0,
            "imu_roll_raw_deg": 0,
            "imu_pitch_gravity_deg": 0,
            "imu_roll_gravity_deg": 0,
            "imu_pitch_zero_deg": 0,
            "imu_roll_zero_deg": 0,
            "imu_neutral_calibrated": False,
        }

        return {
            **latest,
            "latest": latest,
            "nod_count": self.nod_count,
            "history": list(self.history),
        }
